# Generated by Django 4.1.6 on 2023-03-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='site_url',
            field=models.TextField(blank=True),
        ),
    ]
